#pragma once
#include <http/connection/connection_type.h>
#include <http/connection/details/http_connection_type.h>

__synapse_http_connection_handle_tcp*
__synapse_http_connection_tcp_initialize_from_v4	(synapse_http_connection_addr_v4);

__synapse_http_connection_handle_tcp*
__synapse_http_connection_tcp_initialize_from_v6    (synapse_http_connection_addr_v6);

__synapse_http_connection_handle_tcp*
__synapse_http_connection_tcp_initialize_v4_from_url(synapse_http_connection_addr_url);

__synapse_http_connection_handle_tcp*
__synapse_http_connection_tcp_initialize_v6_from_url(synapse_http_connection_addr_url);

void __synapse_http_connection_tcp_cleanup          (__synapse_http_connection_handle_tcp*);